### ISSUE TITLE
Little UI tweak

### ISSUE THREAD

**Issue by sanjevirau** [sanjevirau/gsubs#1]
## Introduction
gSubs's user interface was initially designed before getting into the development. Throughout the development, gSubs was developed to look as close as possible as designed, yet some of the small things couldn't be achieved. I would like to ask for help to implement these little UI tweaks as it will make gSubs look better.

## Initial Design
![home](https://user-images.githubusercontent.com/2032047/37976860-045f2e10-3215-11e8-8710-e09d6f8c80f1.png)

## Final Result
![main home](https://user-images.githubusercontent.com/2032047/37977099-a987c7da-3215-11e8-81a4-aee79db3a54a.PNG)

## The part needs to be tweaked
![tweak needed](https://user-images.githubusercontent.com/2032047/37977631-bafaa5a4-3216-11e8-9ce6-b11d638253d8.png)

**The tweaks needed are mentioned below  :**

**1. Make gSubs corners rounded**
**2. Fix the circular dots**

I have tried doing the rounded corners with @electron transparency support for it's browser window and some CSS, but still can't achieve it. It would be great for us to test @electron full potential.

Thank you.

**Comment by dpnkrpl** [comment]
I love the UI very very much. can I use this UI to build my own QR code reader app?  because I'm not a good artist :). can you please fork my (minimal-weather) repo to improve the UI?
https://github.com/deep5050/minimal-weather

**Comment by sanjevirau** [comment]
Hey @deep5050,
I personally think this is not a place to comment regarding UI as this is an issue ongoing. Anyway, since you brought up the comment, thank you for the compliment regarding the UI ;)! I would love to help you on your UI, unfortunately I don't get much time now days.  I still can help I guess, I will include the design source file (.XD File) which I designed using Adobe XD in this repo. I hope you can use the design source to improve your project. If I got time, I will definitely fork and help on your project.

Thanks you.

**Comment by sanjevirau** [comment]
Hey @deep5050, I have added the UI source and you can get it [here](https://github.com/sanjevirau/gsubs/blob/master/ui-source/gSubs.xd).

Thank you.

**Comment by dpnkrpl** [comment]
Thank you so much. Sorry actually i'm new to github :). Thanks again  for
the file.
