### ISSUE TITLE
Wrong flag for Swedish

### ISSUE THREAD

**Issue by jackbillstrom** [sanjevirau/gsubs#15]
Shold be 🇸🇪

![screen-gsubs](https://user-images.githubusercontent.com/1582303/56212198-d39abc80-6059-11e9-8f26-51f0914fd98a.png)

**Comment by sanjevirau** [comment]
Hi @jackbillstrom, this issue was fixed in the recent version v1.0.3 (https://github.com/sanjevirau/gsubs/releases/tag/v1.0.3). Please download and install it, thanks.
