### ISSUE TITLE
[Feature Request] Make the downloaded subtitle match the title of the video

### ISSUE THREAD

**Issue by ghost** [sanjevirau/gsubs#25]
The program should rename a downloaded subtitle to have exactly the name as the video so we don't have to manually rename it

**Comment by nastyagrifon** [comment]
They should be the exact same name already

<details> <summary>Screenshot</summary>

![Screenshot_2020-10-11_19-04-51](https://user-images.githubusercontent.com/14854919/95682221-c9c12d80-0bec-11eb-8558-0a74c16c6b02.jpg)
</details>

Could you show an example of what you're getting?

**Comment by sanjevirau** [comment]
@joao44289 It's built to change the name accordingly. @NastyaGrifon Thanks for the help :D
