### ISSUE TITLE
What do you need to release for mac ?

### ISSUE THREAD

**Issue by SaraVieira** [sanjevirau/gsubs#3]
Hey !

This is amazing ! I just cloned and built for mac and it works great !

What do you need to release it ?

Can I help ?

**Comment by sanjevirau** [comment]
Thanks @SaraVieira for the complements.

There are specifically 2 reason why I didn't release gSubs for Mac OS.
1.  I didn't have any Mac machine to debug and test gSubs. Since you said it works great, can I know does the icons are also shown perfectly in the drawer?
2. Most importantly, to make the auto-updater feature work for Mac OS, I need to code sign gSubs. Since code signing needs a developer account which costs $99/year, I thought to wait if I could get any donation in order to release it in Mac OS.

The codes are provided for building for Mac and Linux for developers anyway. Can I know with the problem stated, could you think of any solution to bring gSubs to Mac OS?

Thank you.

**Comment by SaraVieira** [comment]
Hey !

Icons work awesome ! Here are two screenshots:
<img width="1436" alt="screen shot 2018-04-02 at 22 20 22" src="https://user-images.githubusercontent.com/1051509/38216882-24fa987c-36c4-11e8-96c9-66c9948a060d.png">
![screen shot 2018-04-02 at 22 20 16](https://user-images.githubusercontent.com/1051509/38216883-251d1262-36c4-11e8-93ff-943b24cf0a20.png)


About the second one many people don't have the apps on the app store. Examples:
https://there.pm/
https://zeit.co/download
https://www.spectacleapp.com/

I can codesign with my apple account, it's not a developer account but you can put that on the website ! I'll keep this repo under watch and always make sure to upload the new version.
Or I can try to install something like: https://medium.com/how-to-electron/how-to-add-auto-updates-to-your-electron-application-an-up-to-date-guide-d62794a0467d

What do you think?

PS: I think the 99$ a year is incredibly dumb and stops devs from making amazing apps

**Comment by sanjevirau** [comment]
Thanks a lot for the screenshot @SaraVieira. I love looking gSubs in Mac OS. It looks great :)

Regarding the code signing part, could you try to implement the [guide](https://medium.com/how-to-electron/how-to-add-auto-updates-to-your-electron-application-an-up-to-date-guide-d62794a0467d) into gSubs and test if the auto updater is working?

If it does work, then as you stated, you can dist a dmg and sign it and give to me and we can release it in the next version :)

Thank you.

**Comment by SaraVieira** [comment]
Sure will!
I will implement it tomorrow and create a pull request to see if it does work :)

**Comment by sanjevirau** [comment]
Thanks a lot @SaraVieira. Take your time and thanks again for the help 👍

**Comment by sanjevirau** [comment]
In addition to that @SaraVieira, I have read this forum [here](https://discuss.atom.io/t/electron-builder-auto-update-without-paid-certificate/51904) and they wouldn't know whether a developer account needed or not for auto update to work. I personally feel that the documentations regarding code signing in Mac are limited. Therefore, we can stick to our earlier plan, test it out by just code signing it and see if the auto update works.

Moreover, I think the auto-update implementation currently in gSubs works fine. You just need to code sign it and see whether it works or not. If it doesn't work, then I plan to just implement a notification to the users who use gSubs in Mac OS and Linux when there is a new update. They have to manually download the new version. The AppImage for Linux however, does support auto-update.

I think that would be the worst scenario solution, what do you think? And in the next release we could make gSubs true cross-platform. 

Thank you.

**Comment by sanjevirau** [comment]
Hi @SaraVieira,
I have just release a new version of gSubs with folder support and Linux release. gSubs just need a DMG file in order to become true cross-platform.

To build  DMG file, I need a Mac which I do not have now. Could you please build the DMG file of the current master repo and send it to me?

Thank you.

**Comment by sanjevirau** [comment]
I've build and added the DMG file in the release using Mac In Cloud service. gSubs is fully cross-platform now. Thanks for the support 👍

**Comment by sanjevirau** [comment]
Hi @SaraVieira , I hope you're doing fine. Recently gSubs face some issues and was broken. I have solved the issues and merge it into the `master` branch. I need a favour from you. Could you please run the distribution command for DMG on your Mac and send over the dist folder to me for a v1.0.3 release?

I hope you can help me as I'm not having a Mac with me, yet. Thank you very much in advance!! :D

**Comment by SaraVieira** [comment]
hey!


I built it and I am now trying to upload it to dropbox but my upload speed is terrible :(

**Comment by sanjevirau** [comment]
@SaraVieira Thanks a lot Sara. It's nothing urgent, take your time. Whenever you're done can buzz me :)

**Comment by SaraVieira** [comment]
Here is the zip file: https://drive.google.com/file/d/1geKooIhVL-n8t7PBBVXsajeDHBleB7vF/view?usp=sharing

Let me know anything else you may need

**Comment by sanjevirau** [comment]
@SaraVieira Thanks a lot. That's exactly what needed for Mac. I have released the new version, https://github.com/sanjevirau/gsubs/releases/tag/v1.0.3

Thanks once again :D

**Comment by SaraVieira** [comment]
Awesome!! Let me know anything else you may need
