### ISSUE TITLE
Subtitle Sites

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [sanjevirau/gsubs#7]
HI 
Nice App Btw.
Please add more websites for downloading subtitles since it is not working properly for tv shows.
Please add the following site:
http://addic7ed.com/
http://subscene.com/
http://yifysubtitles.com/

**Comment by sanjevirau** [comment]
Hey @Ashutosh-Kukreti, thanks for the compliment. The following site can be added to gSubs as they  provide api support : 
[http://addic7ed.com/](http://addic7ed.com/)

The sources are added into the to do list, and will soon be implemented in gSubs.

Thank you.
