### ISSUE TITLE
Logo Proposal for "GSubs"

### ISSUE THREAD

**Issue by moenawar85** [sanjevirau/gsubs#9]
Hello Sir... I would like to contribute with your project by created a new logo. I'm waiting for your response and answer, If you like it I will give you original file that editable PDF and PNG also. If you have any suggestion with color or something else I will fix it.

![gsubs logo icon_logotype](https://user-images.githubusercontent.com/36834147/38866167-2f8c6020-426a-11e8-915d-c6bf3d158c4c.png)

Best regards, Moenawar.
Thank you indeed.

My Contacts : 
Email : monox.rhtm@gmail.com
Twitter : @moen85
Steemit : http://steemit.com/@moenawar

**Comment by sanjevirau** [comment]
Thanks a lot @moenawar85 , but I don't think a new logo needed.
